elements:

  - name: "Existing Addresses"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [0, 0]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [0, 1]
          span: [1, 4]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Address Line 1"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [2, 0]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [2, 1]
          span: [1, 4]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Address Line 2"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [3, 0]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [3, 1]
          span: [1, 4]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "City"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [4, 0]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [4, 1]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "State or Provence"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [4, 2]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [4, 3]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Postal Code"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [5, 0]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [5, 1]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Country"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [5, 2]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [5, 3]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5
