elements:

  - name: "Mobile Phone"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [0, 0]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [0, 1]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Landline"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [0, 2]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [0, 3]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Fax Line"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 0]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [1, 1]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Email Address"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 2]
            span: [1, 1]
            style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 5
      - widget:
          position: [1, 3]
          span: [1, 1]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5
