elements:

  - name: "Datafile"
    has_labels: false
    has_control: true
    items:
      - widget:
          position: [0, 0]
          span: [1, 2]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]

  - name: "InfoBar"
    has_labels: false
    has_control: true
    items:
      - widget:
          position: [1, 0]
          span: [2, 10]
          style: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
