# Needed to keep GBSizerInterface happy; this should NOT be run through the group generator
groups:
  first_run_page:
    run_generator: true
    title: "First Run"
    layout: "FirstRunPage"
    rows: 2
    cols: 1
    growable_cols: [0]
    growable_rows: [0, 1]
    elements:
      - identity: "Name Details"
        items:
          - widget:
              variable: "m_nameGroup"
              tag: "NameDetails"
              class: "NewUserGroup"
              base_class: "Group"
              value: "Name Details"
              is_group: true
              module: "NewUser.Group"
              sizer:
                position: [0, 0]
                flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]

      - identity: "Datafile"
        items:
          - widget:
              variable: "m_filenameGroup"
              tag: "Datafile"
              class: "FilenameGroup"
              base_class: "Group"
              value: "Datafile"
              is_group: true
              module: "Filename.Group"
              sizer:
                position: [1, 0]
                flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
