tables:

  addresses:
    fields:
      id:
        type: integer
        auto_increment: true
        primary_key: true
      fAddressLine1:
        type: string
        not_null: true
      fAddressLine2:
        type: string
      fCity:
        type: string
        not_null: true
      rStateID:
        type: integer
      fCountry:
        type: string
      fPostCode:
        type: string
    relationships:
      - name: r_address_state
        as: state
        type: many_to_one
        foreign_key: rStateID
        references_table: states
        references_field: id
        replace_with: [ "fAbbreviation" ]
        replace_as: state
        cascade_delete: false
    indexes:
      - name: idx_address_state
        fields: [rStateID]
        unique: false

