rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libyaml-cppd.so.0.9
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libyaml-cppd.so
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libsoci_core.so.4
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libsoci_core.so
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libsoci_sqlite3.so.4
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libsoci_sqlite3.so
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwx_gtk3u-3.3.so.3
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwx_gtk3u-3.3.so
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwxsharpyuv-3.3.so.0
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwxsharpyuv-3.3.so
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwxwebp-3.3.so.7
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwxwebp-3.3.so
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwxwebpdemux-3.3.so.2
rm ~/dev/stage/linux/debug/shared/usr/local/lib64/libwxwebpdemux-3.3.so
rm ~/dev/stage/linux/debug/shared/usr/local/bin/HealthCanvas
