groups:
  verbatim:
    body: |
      hs::string_v  maleNames;
      hs::string_v  femaleNames;
      wxArrayString combinedNames;
  brief_user:
    sizer:
      rows: 2
      cols: 4
      growable_cols: [ 1, 3 ]

    class: "BriefUserGroup"
    base_class: "Group"
    functions:
      onChange:
        args: "wxEvent &event"
        return: void
        body: |
          TraceCall;
          event.Skip();
    
          auto showSample = [this] {
            auto fnf = m_FNF->live();
            auto title = m_Title->getSelectedText();
            auto given = m_GivenName->ctl_typed()->GetValue();
            auto family = m_FamilyName->ctl_typed()->GetValue();
            auto first = fnf ? family : given;
            auto last = fnf ? given : family;
            
            if (!title.empty())
              title += " ";
            
            if (!first.empty() && !last.empty())
              first += " ";
    
            auto sample = title + first + last;
            m_FNF->label("FNFSample").first->SetLabel((sample).c_str());
          };
          
          if (event.GetEventObject() == m_Title->ctl()) {
            m_Title->transferFromWindow();
            static bool first = true;
            if (first && m_Title->changed()) {
              ctl_typed()->CallAfter([this] { ctl_typed()->NavigateIn(); });
              first = false;
            }
          
          } else if (event.GetEventObject() == m_GivenName->ctl() && !m_Title->changed()) {
            if (std::ranges::find(maleNames, m_GivenName->live()) != maleNames.end()) {
              m_Title->setSelection("Mr.");
              m_Title->transferFromWindow();
            } else if (std::ranges::find(femaleNames, m_GivenName->live()) != femaleNames.end()) {
              m_Title->setSelection("Ms.");
              m_Title->transferFromWindow();
            }
          }
          showSample();
    title: "New User"
    layout: "BriefUserGroup"

    # Array of ControlSets
    elements:
      - identity: "Title"
        tool_tip: "Choose this person's title"

        items:
          - widget:
              variable: "m_Title"
              tag: "Title"
              size: "sizeLabel"
              class: "mc::TitlesChoice"
              base_class: "Choice"
              uicreateflags: "ExcludeFromColour"
              module: [ "Titles.Choice", "Choice", "StaticText" ]
              contains: "ID::Type"
              style: [ "wxTE_PROCESS_ENTER" ]
              table: "titles"
              field: "fAbbreviation"

              handlers:
                - event: "EVT_CHOICE"          # Single Handler
                  handler: onChange(event);
              # Validator
              validator:
                class: "ComboLikeValidator"
                transfer_model: "ByClientData"
                allow_empty: true

              # Sizer
              sizer:
                position: [ 0, 0 ]
                flags: [ "fixed_control" ]
                proportion: 1

              verbatim:
                body: |
                  m_Title->loadFromDB();

      - identity: "Given Name"
        has_labels: false
        has_control: true
        tool_tip: "Enter their given name (mandatory). If they only have one name, enter it here"
        items:
          - widget:
              variable: "m_GivenName"
              tag: "Given Name"
              size: "sizeCtrl"
              class: "TextCtrl"
              module: "TextCtrl"
              contains: "std::string"
              style: [ "wxTE_PROCESS_ENTER" ]
              table: "users"
              field: "fGivenName"

              # Array of Handlers
              handlers:
                - event: "EVT_TEXT"          # Single Handler
                  handler: onChange(event);

                # more Handlers ...

              # Validator
              validator:
                class: "CapsValidator"
                allow_empty: false
                tool_tip: "Given name cannot be empty"

              # Sizer
              sizer:
                position: [ 0, 1 ]
                flags: [ "expanding_control" ]
                proportion: 5

              verbatim:
                body: |
                  if (maleNames.empty()) {
                    Util::getInstance().readFile (Util::getInstance().resourceName (UIType::List, "males", false), maleNames);
                    for (auto &man : maleNames)    combinedNames.push_back (man.c_str());
                  }
                  if (femaleNames.empty()) {
                    Util::getInstance().readFile (Util::getInstance().resourceName (UIType::List, "females", false), femaleNames);
                    for (auto &woman : femaleNames)  combinedNames.push_back (woman.c_str());
                  }
                  m_GivenName->ctl_typed()->AutoComplete (combinedNames);

      - identity: "Family Name"       # Single ControlSet
        has_labels: true
        has_control: true
        tool_tip: "Enter their family name. If they don't have one, leave empty"
        items:
          - labels:
              - key: "LIX::Main"
                tag: "FamilyNameLabel"
                size: sizeLabel
                class: "MarkupText"
                value: "Family Name"
                style: [ "wxALIGN_RIGHT", "wxALIGN_CENTER_VERTICAL" ]
                sizer:
                  position: [ 0, 2 ]
                  flags: [ "right_label" ]
                  proportion: 1
          - widget:
              variable: "m_FamilyName"
              tag: "Family Name"
              class: "TextCtrl"
              module: "TextCtrl"
              contains: "std::string"
              style: [ "wxTE_PROCESS_ENTER" ]
              size: sizeCtrl
              table: "users"
              field: "fFamilyName"
              handlers:
                - event: "EVT_TEXT"          # Single Handler
                  handler: onChange(event);
              validator:
                class: "CapsValidator"
                allow_empty: true
                tool_tip: "Given name cannot be empty"
              sizer:
                position: [ 0, 3 ]
                flags: [ "expanding_control" ]
                proportion: 5
      - identity: "Family Name First"       # Single ControlSet
        has_labels: true
        has_control: true
        tool_tip: "Select if the family name is printed first (like Chinese)"
        items:
          - widget:
              variable: "m_FNF"
              tag: "Family Name First"
              size: "sizeLabel"
              class: "CheckBox"
              module: "CheckBox"
              contains: "bool"
              style: [ "wxTE_PROCESS_ENTER", "wxALIGN_RIGHT" ]
              table: "users"
              field: "bFNF"
              handlers:
                - event: "EVT_CHECKBOX"          # Single Handler
                  handler: onChange(event);
              validator:
                class: "GenericValidator"
                allow_empty: true

              sizer:
                position: [ 1, 0 ]
                flags: [ "fixed_control", "wxALIGN_RIGHT" ]
                proportion: 1
          # Array of Labels
          - labels:
              - key: "LIX::Main"
                tag: "FNFLabel"
                size: "sizeCtrl"
                class: "MarkupText"
                value: "Family name comes first"
                #                style: [ "wxALIGN_CENTER_VERTICAL", "wxALIGN_LEFT" ]
                sizer:
                  position: [ 1, 1 ]
                  flags: [ "left_label", wxGROW ]
                  proportion: 5
              - key: "LIX::Second"
                tag: "FNFSample"
                class: "MarkupText"
                #                style: [ "wxALIGN_CENTER_VERTICAL", "wxALIGN_RIGHT" ]
                size: "sizeCtrl"
                sizer:
                  position: [ 1, 3 ]
                  #                  flags: [ "right_label", "wxGROW" ]
                  proportion: 5