groups:
  email_alerts:
    title: "Email Alerts"
    layout: EmailAlertsGroup
    sizer:
      rows: 3
      cols: 7
      growable_cols: [2, 4, 6]

    args:
      arg_name: emailAlertArgs
      args_in: [
        min, int, 0,
        max, int, 60
      ]

    elements:
      - identity: "Use Email Alerts"
        tool_tip: "Should Email Alerts be generated for events?"

        items:
          - widget:
              variable: m_useEmails
              tag: "Use Email Alerts"
              class: CheckBox
              module: CheckBox
              contains: bool
              style: [ wxALIGN_CENTER ]
              table: settings
              field: fUseEmails
              validator:
                class: GenericValidator
                allow_empty: false

              sizer:
                position: [0, 0]
                flags: [ wxALIGN_CENTER, wxALL ]
          - labels:
            - key: LIX::Main
              size: sizeLabel
              tag: UseEmailAlertsLabel
              class: MarkupText
              value: "Send Email"
              style: [ wxALIGN_LEFT, wxALIGN_CENTER_VERTICAL ]

              sizer:
                position: [0, 1]
                flags: [ wxALIGN_LEFT, wxALIGN_CENTRE_VERTICAL, wxALL ]

      - identity: "Server Address"
        tool_tip: "The URL of the SMTP Email Server to send from"
        items:
          - labels:
              - key: LIX::Main
                size: sizeLabel
                tag: ServerAddressLabel
                class: MarkupText
                value: URL
                style: [ wxALIGN_RIGHT, wxALIGN_CENTER_VERTICAL ] #, wxALL ]

                sizer:
                  position: [1, 1]
                  flags: [ wxALIGN_RIGHT, wxALIGN_CENTRE_VERTICAL, wxALL ]

          - widget:
              variable: m_serverAddress
              tag: "Server Address"
              size: sizeCtrl
              class: TextCtrl
              module: TextCtrl
              contains: std::string
              style: [ wxALIGN_LEFT, wxTE_PROCESS_ENTER ]
              table: settings
              field: fEmailServer

              validator:
                class: DomainValidator
                allow_empty: false

              sizer:
                position: [1, 2]
                flags: [ wxALIGN_CENTRE_VERTICAL, wxGROW, wxALL ]
                proportion: 100

      - identity: "Server User"
        tool_tip: "The login user for the SMTP Email Server"
        items:
          - labels:
              - key: LIX::Main
                size: sizeLabel
                tag: ServerUserLabel
                class: MarkupText
                value: User
                style: [ wxALIGN_RIGHT, wxALIGN_CENTER_VERTICAL ]

                sizer:
                  position: [1, 3]
                  flags: [ wxALIGN_RIGHT, wxALIGN_CENTRE_VERTICAL, wxALL ]

          - widget:
              variable: m_serverUser
              tag: "Server User"
              size: sizeCtrl
              class: TextCtrl
              module: TextCtrl
              contains: std::string
              style: [ wxALIGN_LEFT, wxTE_PROCESS_ENTER ]
              table: settings
              field: fEmailUser

              validator:
                class: EmailValidator
                allow_empty: false

              sizer:
                position: [1, 4]
                proportion: 100
                flags: [ wxALIGN_CENTRE_VERTICAL, wxGROW, wxALL ]

      - identity: "Server Password"
        tool_tip: "The login password for the SMTP Email Server"
        items:
          - labels:
              - key: LIX::Main
                size: sizeLabel
                tag: ServerPasswdLabel
                class: MarkupText
                value: Password
                style: [ wxALIGN_RIGHT, wxALIGN_CENTER_VERTICAL ]

                sizer:
                  position: [1, 5]
                  flags: [ wxALIGN_RIGHT, wxALIGN_CENTRE_VERTICAL, wxALL ]

          - widget:
              variable: m_serverPassword
              tag: "Server Password"
              size: sizeCtrl
              class: TextCtrl
              module: TextCtrl
              contains: std::string
              style: [ wxALIGN_LEFT, wxTE_PROCESS_ENTER, wxTE_PASSWORD ]
              table: settings
              field: fEmailPassword

              validator:
                class: GenericValidator
                allow_empty: false

              sizer:
                position: [1, 6]
                proportion: 100
                flags: [ wxALIGN_CENTRE_VERTICAL, wxGROW, wxALL ]

      - identity: "Server Authority"
        tool_tip: "The SMTP Email Server Authority type"

        items:
          - labels:
              - key: LIX::Main
                size: sizeLabel
                tag: ServerAuthorityLabel
                class: MarkupText
                value: Authority
                style: [ wxALIGN_RIGHT, wxALIGN_CENTER_VERTICAL ]

                sizer:
                  position: [2, 1]
                  flags: [ wxALIGN_RIGHT, wxALIGN_CENTRE_VERTICAL, wxALL ]

          - widget:
              variable: m_serverAuthority
              tag: "Server Authority"
              size: sizeCtrlComboLike
              class: mc::EmailAuthorityCombo
              base_class: Combo
              module: EmailAuthority.Combo
              contains: ID::Type
              style: [ wxALIGN_LEFT, wxTE_PROCESS_ENTER, wxCB_READONLY ]
              table: settings
              field: fEmailAuthority
#              uicreateflags: [ NoDefaultBinds ]
              validator:
                class: ComboLikeValidator
                transfer_model: ByClientData
                allow_empty: false

              sizer:
                position: [2, 2]
                proportion: 100
                flags: [ wxALIGN_CENTRE_VERTICAL, wxGROW, wxALL ]
#
#              handlers:
#                - event: "wxEVT_COMBOBOX_DROPDOWN"
#                  handler: |
#                    event.Skip();
#                - event: "wxEVT_COMBOBOX_CLOSEUP"
#                  handler: |
#                    event.Skip();
              verbatim:
                body: |
                   m_serverAuthority->loadFromDB();
      - identity: "Server Security"
        tool_tip: "The SMTP Email Server Security type"

        items:
          - labels:
              - key: LIX::Main
                size: sizeLabel
                tag: ServerSecurityLabel
                class: MarkupText
                value: Security

                sizer:
                  position: [2, 3]
                  flags: [ wxALIGN_RIGHT, wxALIGN_CENTRE_VERTICAL, wxALL ]

          - widget:
                base_class: Combo
                class: mc::EmailSecurityCombo
                contains: ID::Type
                field: fEmailSecurity
                module: EmailSecurity.Combo
                size: sizeCtrlComboLike
                style: [ wxALIGN_LEFT, wxTE_PROCESS_ENTER, wxCB_READONLY ]
                table: settings
                tag: "Server Security"
#                uicreateflags: [ NoDefaultBinds ]
                variable: m_serverSecurity

                validator:
                  class: ComboLikeValidator
                  transfer_model: ByClientData
                  allow_empty: false

                sizer:
                  position: [2, 4]
                  proportion: 100
                  flags: [ wxALIGN_CENTRE_VERTICAL, wxGROW, wxALL ]
#                handlers:
#                  - event: "wxEVT_COMBOBOX_DROPDOWN"
#                    handler: |
#                      event.Skip();
#                  - event: "wxEVT_COMBOBOX_CLOSEUP"
#                    handler: |
#                      event.Skip();
                verbatim:
                  body: |
                    m_serverSecurity->loadFromDB();

      - identity: "Server Timeout"
        tool_tip: "The SMTP Email Server Timeout value"
        items:
          - labels:
              - key: LIX::Main
                size: sizeLabel
                tag: ServerTimeoutLabel
                class: MarkupText
                value: Timeout (Sec)
                style: [ wxALIGN_RIGHT, wxALIGN_CENTER_VERTICAL ]
                sizer:
                  position: [2, 5]
                  flags: [ wxALIGN_RIGHT, wxALIGN_CENTRE_VERTICAL, wxALL ]

          - widget:
              variable: m_serverTimeout
              tag: "Server Timeout"
              size: sizeCtrlSpin
              class: SpinCtrl
              module: SpinCtrl
              style: [ wxSP_ARROW_KEYS, wxTE_PROCESS_ENTER, wxALIGN_CENTRE_HORIZONTAL ]
              contains: int
              value: 30
              table: settings
              field: fEmailTimeout

              validator:
                class: GenericValidator
                allow_empty: false

              sizer:
                position: [2, 6]
                flags: [ wxALIGN_CENTRE_VERTICAL, wxALL, wxGROW ]
