groups:
  filename:
    sizer:
      cols: 3
      growable_cols: [1]

#    args:
#      arg_name: "filenameGroupArgs"
#      args_in: [ "layoutPath", "std::string", "NameGroup" ]
#      args_out: [ "anArgOut", bool, "true" ]

    functions:
      onSelect:
        args: "wxCommandEvent &event"
        return: void
        body: |
          TraceCall;
          auto newName = Util::getInstance().saveFileDialog ("New Datafile",
                  (Util::getInstance().getDocumentsDir() / (hs::appName() + "." + hs::mdiDocExtn())).string().c_str());
          if ( newName.empty() ) {
              return;
          }
          if ( fs::exists (newName) ) {
              fs::remove (newName);
          }         
          m_filenameText->live (newName);
          m_filenameText->transferToWindow();
    elements:
      - identity: "Filename"
        tool_tip: "Enter filename here or click on 'Select' to browse"
        verbatim:
          body: |
            fs::path path = Util::getInstance().getDocumentsDir() / (hs::appName() + "." + hs::mdiDocExtn());
            if ( !fs::exists (path.parent_path()) ) {
                fs::create_directories (path.parent_path());
            }
        items:
          - labels:
              - key: "LIX::Main"
                tag: "FilenameLabel"
                class: "MarkupText"
                value: "Filename"
                style: [ "wxALIGN_CENTRE_VERTICAL", "wxALIGN_RIGHT" ]

                sizer:
                  position: [ 0, 0 ]
                  flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT" ]

          - widget:
              variable: "m_filenameText"
              tag: "Filename"
              class: "TextCtrl"
              module: "TextCtrl"
              contains: "std::string"
              style: [ "wxTE_PROCESS_ENTER" ]
              size: "sizeCtrlLarge"

              validator:
                class: "GenericValidator"
                allow_empty: false
                tool_tip: "Filename must be specified"

              sizer:
                position: [ 0, 1 ]
                proportion: 10
                flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW" ]

              verbatim:
                body: m_filenameText->initialize (path.string());

      - identity: "Select"
        tool_tip: "Click here to open a file selection dialog box"
        items:
          - widget:
              variable: "m_selectButton"
              tag: "Select Button"
              class: "Button"
              value: "Select"
              base_class: wxButton
              module: "Button"
              uicreateflags: "ExcludeFromColour"
              size: "sizeCtrlButton"
#
              sizer:
                position: [ 0, 2 ]
                flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL" ]
              handlers:
                - event: "wxEVT_COMMAND_BUTTON_CLICKED"
                  handler: |
                    event.Skip();
                    onSelect(dynamic_cast<wxCommandEvent&>(event));









#      - identity: "Select"
#        tool_tip: "Click here to open a file selection dialog box"
#        items:
#          - widget:
#              variable: "m_selectButton"
#              tag: "Select Button"
#              class: "Button"
#              module: "Button"
#              value: "Select"
#              uicreateflags: "ExcludeFromColour"
#              handlers:
#                - event: "wxEVT_COMMAND_BUTTON_CLICKED"
#                  handler: |
#                    event.Skip();
#                    onSelect(dynamic_cast<wxCommandEvent&>(event));
#              sizer:
#                position: [ 0, 2 ]
#                flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL" ]










































