pages:
  general_settings:
    sizer:
      cols: 1
      rows: 7
      growable_cols: [ 0 ]
      growable_rows: [ 0, 1, 2, 3, 4, 5, 6 ]

    args:
      arg_name: "generalSettingsPageArgs"
      args_in: [ "pageName", "std::string", "General",
                 "splitWindow", "bool", "false"
      ]
#
#    on_kill_active:
#      body: |
#        // Yadda yadda yadda
#           Interface::onKillActive(autoDisable);
    base_class: Page
    module: Page

    title: "General Settings"
    layout: "GeneralSettingsPage"
    elements:
      - identity: "PopupAlerts"
        tool_tip: "Global setting to enable/disable and configure popups"
        items:
          - widget:
              variable: "m_popupAlerts"
              tag: "PopupAlerts"
              value: "Popup Alerts"
              class: "PopupAlertsGroup"
              base_class: "Group"
              uicreateflags: "Group"
              module: [ "PopupAlerts.Group" ]
              sizer:
                position: [ 1, 0 ]
                flags: [ "wxALL", "wxGROW" ]
                border: 10
                proportion: 100
      - identity: "EmailAlerts"
        tool_tip: "Global setting to enable/disable and configure emails"
        items:
          - widget:
              variable: "m_emailAlerts"
              tag: "EmailAlerts"
              value: "Email Alerts"
              class: "EmailAlertsGroup"
              base_class: "Group"
              uicreateflags: "Group"
              module: [ "EmailAlerts.Group" ]
              sizer:
                position: [ 3, 0 ]
                flags: [ "wxALL", "wxGROW" ]
                border: 10
                proportion: 100
      - identity: "SMSAlerts"
        tool_tip: "Global setting to enable/disable and configure SMSes"
        items:
          - widget:
              variable: "m_SMSAlerts"
              tag: "SMSAlerts"
              value: "SMS Alerts"
              class: "SmsAlertsGroup"
              base_class: "Group"
              uicreateflags: "Group"
              module: [ "SmsAlerts.Group" ]
              sizer:
                position: [ 5, 0 ]
                flags: [ "wxALL", "wxGROW" ]
                border: 10
                proportion: 100
