wizardpages:
  new_datafile:
    title: Basic Details
    layout: NewDatafileWizardPage
    sizer:
      rows: 2
      cols: 1
      growable_cols: [0]
      growable_rows: [0, 1]
    args:
      arg_name: "newDatafileArgs"
      args_in: [ "dunnoMaybe", "std::string", "Welcome" ]

    elements:
      - identity: "Name Details"
        items:
          - widget:
              variable: m_nameGroup
              tag: "Name Details"
              class: BriefUserGroup
              base_class: Group
              value: "Name Details"
              is_group: true
              module: BriefUser.Group
              sizer:
                position: [0, 0]
                flags: [wxALIGN_CENTRE_VERTICAL, wxALL, wxGROW]
                proportion: 1

      - identity: Datafile
        items:
          - widget:
              variable: m_filenameGroup
              tag: Datafile
              class: FilenameGroup
              base_class: Group
              value: Datafile
              is_group: true
              module: Filename.Group
              sizer:
                position: [1, 0]
                flags: [wxALIGN_CENTRE_VERTICAL, wxALL, wxGROW]
                proportion: 1
