groups:
  popup_alerts:
    title:                    Popup Alerts
    layout:                   PopupAlertsGroup
    sizer:
      cols:                   2
      growable_cols:          [ 1 ]

    elements:
      - identity:             "Use Popup Alerts"
        tool_tip:             "Should Popup Alerts be generated for events?"
        items:
          - widget:
              variable:       m_usePopupAlerts
              tag:            "Use Popup Alerts"
              class:          CheckBox
              module:         CheckBox
              contains:       bool
              style:          [ wxALIGN_CENTER ]
              table:          settings
              field:          fUsePopupAlerts
              validator:
                class:        GenericValidator
                allow_empty:  false

              sizer:
                position:     [0, 0]
                proportion:   1
                flags:        [ wxALIGN_CENTER, wxALL ]

          - labels:
              - key:          LIX::Main
                tag:          UsePopupAlertsLabel
#                size: "sizeLabel"
                class:        MarkupText
                value:        "Use Popups"
                style:        [ wxALIGN_CENTER_VERTICAL ]
                sizer:
                  position:   [0, 1]
                  proportion: 100
                  flags:      [ wxALIGN_CENTRE_VERTICAL, wxALL, wxGROW ]
