pages:
  users:
#    sizer:
#      cols: 1
#      rows: 7
#      growable_cols: [ 0 ]
#      growable_rows: [ 0, 1, 2, 3, 4, 5, 6 ]

    args:
      arg_name: "usersArgs"
      args_in: [ "pageName", "std::string", "General",
                 "splitWindow", "bool", "false"
      ]
#
#    on_kill_active:
#      body: |
#        // Yadda yadda yadda
#           Interface::onKillActive(autoDisable);

    base_class: SplitterPage
    modules: ["SplitterPage", "Users.RS"]
    title: "Users"
    layout: "Users"
    elements:

    functions:
      select:
        return: "soci::rowset<>"
        override: True
        body: |
          auto rs = mc::UsersRS(*ICtrl::db()->getTable("users"));
          return rs.getRowset("id = 1");

tables:
  users:
    fields:
      id:
        type: integer
        auto_increment: true
        primary_key: true
      fGivenName:
        type: string
        not_null: true
      fFamilyName:
        type: string
      bFNF:
        type: hs_bool
      rTitleID:
        type: integer
      bAdmin:
        type: hs_bool
      dDateOfBirth:
        type: date
      dDateOfDeath:
        type: date
      fMCNumber:
        type: string
      fMCIndex:
        type: integer
      fMCExpiry:
        type: date
      rDoctorID:
        type: integer
      rPharmacyID:
        type: integer
      bWantsEmailAlerts:
        type: hs_bool
      bWantsPopupAlerts:
        type: hs_bool
      bWantsSMSAlerts:
        type: hs_bool
      bConcession:
        type: hs_bool
      rAddressID:
        type: integer
      rPostalAddressID:
        type: integer

    relationships:
      - name: r_user_title
        as: title
        type: many_to_one
        foreign_key: rTitleID
        references_table: titles
        references_field: id
        replace_with: [ fAbbreviation ]
        replace_as: title
        cascade_delete: true
      - name: r_user_doctor
        as: doctor
        type: many_to_one
        foreign_key: rDoctorID
        references_table: doctors
        references_field: id
        replace_with: [ fGivenName, fFamilyName ]
        replace_as: doctor
        cascade_delete: true
      - name: r_user_pharmacy
        as: pharmacy
        type: many_to_one
        foreign_key: rPharmacyID
        references_table: locations
        references_field: id
        cascade_delete: true
      - name: r_user_address
        as: address
        type: many_to_one
        foreign_key: rAddressID
        references_table: addresses
        references_field: id
        replace_with: [ fAddressLine1, fAddressLine2, fCity ]
        replace_as: address
        cascade_delete: true
      - name: r_user_postal_address
        as: postal_address
        type: many_to_one
        foreign_key: rPostalAddressID
        references_table: addresses
        references_field: id
        replace_with: [ fAddressLine1, fAddressLine2, fCity ]
        replace_as: postal_address
        cascade_delete: true

    indexes:
      - name: idx_user_title
        fields: [rTitleID]
        unique: false
