// Created by geoffrey on 8/3/24.
//

#include "MyCare/App.h"
#include "Core/CoreData.h"
#include "Core/Core.h"
#include "Core/TraceLevel.h"
#include "Core/VerifyAppConfigChecksum.h"
#include "Gfx/Widgets.h"
#include "Gfx/wx.h"
#include <wx/stdpaths.h>
#include <wx/filename.h>
#include <iostream>
#include <stdexcept>

import Util;
import DDT;
import LogSignals;
import SystemSignals;
import SplashSignals;
import Types;
import MC.Frame;
import MC.DBManager;
import SplashFrame;


// These are defined in the .cpp file generated by CMake/xxd for MyCare
extern const char app_config_yaml[];
extern const unsigned int app_config_yaml_len;

static struct EarlyConfigLoader {
   EarlyConfigLoader() {
      // This runs during global static initialization
      hs::setEmbeddedConfig(app_config_yaml, app_config_yaml_len);
#if defined(__linux__)
      // Force X11 backend so WebKit2GTK compositing works under Wayland
      setenv("GDK_BACKEND", "x11", 0); // 0 = don't override if user set it explicitly
#endif
   }
} g_earlyConfigLoader; // 2. Create a global instance of it

namespace mc {

App::App() : CApp() {

   // throw std::runtime_error("Boo!");
   debug_break();
   TraceCall;
   wx::pApp(this);
}

App::~App() { TraceCall; }

auto App::OnInit() -> bool {
   TraceCall;

   if (CApp::OnInit()) {
      SplashFrame *splash = nullptr;
      if (m_showSplashScreenOnStartup) {
	     SplashFrame::Config cfg;
         cfg.background = SplashFrame::Config::CreateSplashBitmap(hs::appName(), hs::appDescription(), hs::appVersion(),
                                                                  "Please wait...");
         cfg.initialMessage = "";
         cfg.centerOnScreen = true;

         splash = new SplashFrame(cfg);
         Yield();
      }

      hs::splashSignal().Message("Creating Frame");
      auto frame = new mc::Frame();
      TraceIf(TraceLevel::Status)
         dout << "app::frame = " << Util::getInstance().intToVoidPtr(reinterpret_cast<long long>(frame)) << std::endl;

      hs::splashSignal().Message("Creating DB Manager");
      auto manager = new mc::DBManager();
      TraceIf(TraceLevel::Status)
         dout << "   manager = " << Util::getInstance().intToVoidPtr(reinterpret_cast<long long>(manager)) << std::endl;

      hs::splashSignal().Message("Initializing Frame");
      auto frameOk = frame->Create(manager, nullptr, wx::nextID(), hs::appName());
      TraceIf(TraceLevel::Status)
         dout << "Create Ok? = " << frameOk << std::endl;

      if (frameOk) {
         hs::isRunning(true);
         hs::systemSignal().Running();
         hs::enableLogger(true);
         delete splash;
         return true;
      }
   }

   return false;
}

auto App::DialogBoxText(const std::string &which) -> std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> {
   TraceCall;

   if (which == "AboutBox") {
      auto html = Util::getInstance().readFile(Util::getInstance().resourceName(UIType::Html, "About.html", true));

      hs::HtmlDialog::HtmlDialogInfo is(hs::appDescription(), "A HoffSoft production", html, wxICON_INFORMATION,
                                        550, 250, {},
                                        {});
      std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> info = std::make_shared<hs::HtmlDialog::HtmlDialogInfo>(is);
      return info;
   }
   if (which == "FileHandlerFileMissing") {
      auto html = Util::getInstance().readFile(Util::getInstance().resourceName(UIType::Html, "FileHandlerFileMissing.html", true));

      hs::HtmlDialog::HtmlDialogInfo is("Something's not quite right...", "Your attention is required", html, wxICON_QUESTION,
                                        550, 250, {},
                                        {});
      std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> info = std::make_shared<hs::HtmlDialog::HtmlDialogInfo>(is);
      return info;
   }
   if (which == "FileHandlerMRUMissing") {
      auto html = Util::getInstance().readFile(Util::getInstance().resourceName(UIType::Html, "FileHandlerMRUMissing.html", true));

      std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> info = std::make_shared<hs::HtmlDialog::HtmlDialogInfo>();

      info->m_title = "Something's not quite right...";
      info->m_subTitle = "Your attention is required";
      info->m_contents = html;
      info->m_stockIcon = wxICON_QUESTION;
      info->m_minWidth = 640;
      info->m_minHeight = 200;
      info->m_needOutlineFont = true;

      return info;
   }
   if (which == "FileHandlerFileMissingNoMRU") {
      auto html = Util::getInstance().readFile(Util::getInstance().resourceName(UIType::Html, "FileHandlerFileMissingNoMRU.html", true));

      hs::HtmlDialog::HtmlDialogInfo is("Something's not quite right...", "Your attention is required", html, wxICON_QUESTION,
                                        550, 270, {},
                                        {});
      std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> info = std::make_shared<hs::HtmlDialog::HtmlDialogInfo>(is);
      return info;
   }
   if (which == "FileHandlerAsk") {
      auto html = Util::getInstance().readFile(Util::getInstance().resourceName(UIType::Html, "FileHandlerAsk.html", true));

      hs::HtmlDialog::HtmlDialogInfo is("Something's not quite right...", "Your attention is required", html,
                                        wxICON_QUESTION, 550, 210,
                                        {}, {});
      std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> info = std::make_shared<hs::HtmlDialog::HtmlDialogInfo>(is);
      return info;
   }
   if (which == "FileHandlerAskNoMRU") {
      auto html = Util::getInstance().readFile(Util::getInstance().resourceName(UIType::Html, "FileHandlerAskNoMRU.html", true));

      hs::HtmlDialog::HtmlDialogInfo is("Something's not quite right...", "Your attention is required", html,
                                        wxICON_QUESTION, 550, 200,
                                        {}, {});
      std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> info = std::make_shared<hs::HtmlDialog::HtmlDialogInfo>(is);
      return info;
   }
   if (which == "FileHandlerMRUFileMissing") {
      auto html = Util::getInstance().readFile(Util::getInstance().resourceName(UIType::Html, "FileHandlerMRUFileMissing.html", true));

      hs::HtmlDialog::HtmlDialogInfo is("Something's not quite right...", "Your attention is required", html,
                                        wxICON_QUESTION, 640, 230,
                                        {}, {});
      std::shared_ptr<hs::HtmlDialog::HtmlDialogInfo> info = std::make_shared<hs::HtmlDialog::HtmlDialogInfo>(is);
      return info;
   }

   return CApp::DialogBoxText(which);
}
} // namespace mc
wxIMPLEMENT_DYNAMIC_CLASS(mc::App, CApp);
wxIMPLEMENT_APP(mc::App);
